const tickerToSectorSlug: Record<string, string> = {
  THYAO: 'ulasim-lojistik',
  PGSUS: 'ulasim-lojistik',
  TAVHL: 'ulasim-lojistik',
  TUPRS: 'enerji-uretim-dagitim-petrol',
  KCHOL: 'holdingler',
  SAHOL: 'holdingler',
  DOHOL: 'holdingler',
  AKBNK: 'bankacilik-finans',
  GARAN: 'bankacilik-finans',
  YKBNK: 'bankacilik-finans',
  HALKB: 'bankacilik-finans',
  VAKBN: 'bankacilik-finans',
  ISCTR: 'bankacilik-finans',
  EREGL: 'sanayi-metal-kimya',
  KRDMD: 'sanayi-metal-kimya',
  SISE: 'sanayi-metal-kimya',
  SASA: 'sanayi-metal-kimya',
  PETKM: 'sanayi-metal-kimya',
  TRALT: 'sanayi-metal-kimya',
  ASELS: 'otomotiv-savunma-makine',
  TOASO: 'otomotiv-savunma-makine',
  FROTO: 'otomotiv-savunma-makine',
  BIMAS: 'tuketim-perakende-tekstil',
  MGROS: 'tuketim-perakende-tekstil',
  ARCLK: 'tuketim-perakende-tekstil',
  TCELL: 'teknoloji-iletisim',
  TTKOM: 'teknoloji-iletisim',
  ENKAI: 'insaat-yapi-malzemeleri',
  EKGYO: 'gyo-gayrimenkul',
  KOZAL: 'diger',
  KOZAA: 'diger',
}

export default tickerToSectorSlug
