/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakipListesiRouteImport } from './routes/takip-listesi'
import { Route as SirketlerRouteImport } from './routes/sirketler'
import { Route as SektorlerRouteImport } from './routes/sektorler'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EndekslerRouteImport } from './routes/endeksler'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as SektorlerSlugRouteImport } from './routes/sektorler.$slug'
import { Route as PanelProfilRouteImport } from './routes/panel.profil'
import { Route as PanelBorsaRouteImport } from './routes/panel.borsa'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as PanelSirketlerIdRouteImport } from './routes/panel.sirketler.$id'
import { Route as PanelEndekslerIdRouteImport } from './routes/panel.endeksler.$id'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiUserCreditsRouteImport } from './routes/api/user/credits'
import { Route as ApiModelsAvailableRouteImport } from './routes/api/models/available'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiPreCheckRouteImport } from './routes/api/ai/pre-check'
import { Route as ApiAiChargeRouteImport } from './routes/api/ai/charge'

const TakipListesiRoute = TakipListesiRouteImport.update({
  id: '/takip-listesi',
  path: '/takip-listesi',
  getParentRoute: () => rootRouteImport,
} as any)
const SirketlerRoute = SirketlerRouteImport.update({
  id: '/sirketler',
  path: '/sirketler',
  getParentRoute: () => rootRouteImport,
} as any)
const SektorlerRoute = SektorlerRouteImport.update({
  id: '/sektorler',
  path: '/sektorler',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EndekslerRoute = EndekslerRouteImport.update({
  id: '/endeksler',
  path: '/endeksler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const SektorlerSlugRoute = SektorlerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SektorlerRoute,
} as any)
const PanelProfilRoute = PanelProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PanelRoute,
} as any)
const PanelBorsaRoute = PanelBorsaRouteImport.update({
  id: '/borsa',
  path: '/borsa',
  getParentRoute: () => PanelRoute,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelSirketlerIdRoute = PanelSirketlerIdRouteImport.update({
  id: '/sirketler/$id',
  path: '/sirketler/$id',
  getParentRoute: () => PanelRoute,
} as any)
const PanelEndekslerIdRoute = PanelEndekslerIdRouteImport.update({
  id: '/endeksler/$id',
  path: '/endeksler/$id',
  getParentRoute: () => PanelRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreditsRoute = ApiUserCreditsRouteImport.update({
  id: '/api/user/credits',
  path: '/api/user/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsAvailableRoute = ApiModelsAvailableRouteImport.update({
  id: '/api/models/available',
  path: '/api/models/available',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPreCheckRoute = ApiAiPreCheckRouteImport.update({
  id: '/api/ai/pre-check',
  path: '/api/ai/pre-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChargeRoute = ApiAiChargeRouteImport.update({
  id: '/api/ai/charge',
  path: '/api/ai/charge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/endeksler': typeof EndekslerRoute
  '/login': typeof LoginRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/panel': typeof PanelRouteWithChildren
  '/sektorler': typeof SektorlerRouteWithChildren
  '/sirketler': typeof SirketlerRoute
  '/takip-listesi': typeof TakipListesiRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/panel/borsa': typeof PanelBorsaRoute
  '/panel/profil': typeof PanelProfilRoute
  '/sektorler/$slug': typeof SektorlerSlugRoute
  '/panel/': typeof PanelIndexRoute
  '/api/ai/charge': typeof ApiAiChargeRoute
  '/api/ai/pre-check': typeof ApiAiPreCheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/models/available': typeof ApiModelsAvailableRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/panel/endeksler/$id': typeof PanelEndekslerIdRoute
  '/panel/sirketler/$id': typeof PanelSirketlerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/endeksler': typeof EndekslerRoute
  '/login': typeof LoginRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/sektorler': typeof SektorlerRouteWithChildren
  '/sirketler': typeof SirketlerRoute
  '/takip-listesi': typeof TakipListesiRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/panel/borsa': typeof PanelBorsaRoute
  '/panel/profil': typeof PanelProfilRoute
  '/sektorler/$slug': typeof SektorlerSlugRoute
  '/panel': typeof PanelIndexRoute
  '/api/ai/charge': typeof ApiAiChargeRoute
  '/api/ai/pre-check': typeof ApiAiPreCheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/models/available': typeof ApiModelsAvailableRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/panel/endeksler/$id': typeof PanelEndekslerIdRoute
  '/panel/sirketler/$id': typeof PanelSirketlerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/endeksler': typeof EndekslerRoute
  '/login': typeof LoginRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/panel': typeof PanelRouteWithChildren
  '/sektorler': typeof SektorlerRouteWithChildren
  '/sirketler': typeof SirketlerRoute
  '/takip-listesi': typeof TakipListesiRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/panel/borsa': typeof PanelBorsaRoute
  '/panel/profil': typeof PanelProfilRoute
  '/sektorler/$slug': typeof SektorlerSlugRoute
  '/panel/': typeof PanelIndexRoute
  '/api/ai/charge': typeof ApiAiChargeRoute
  '/api/ai/pre-check': typeof ApiAiPreCheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/models/available': typeof ApiModelsAvailableRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/panel/endeksler/$id': typeof PanelEndekslerIdRoute
  '/panel/sirketler/$id': typeof PanelSirketlerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/endeksler'
    | '/login'
    | '/nasil-calisir'
    | '/panel'
    | '/sektorler'
    | '/sirketler'
    | '/takip-listesi'
    | '/api/checkout'
    | '/panel/borsa'
    | '/panel/profil'
    | '/sektorler/$slug'
    | '/panel/'
    | '/api/ai/charge'
    | '/api/ai/pre-check'
    | '/api/auth/$'
    | '/api/models/available'
    | '/api/user/credits'
    | '/api/webhooks/polar'
    | '/panel/endeksler/$id'
    | '/panel/sirketler/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/endeksler'
    | '/login'
    | '/nasil-calisir'
    | '/sektorler'
    | '/sirketler'
    | '/takip-listesi'
    | '/api/checkout'
    | '/panel/borsa'
    | '/panel/profil'
    | '/sektorler/$slug'
    | '/panel'
    | '/api/ai/charge'
    | '/api/ai/pre-check'
    | '/api/auth/$'
    | '/api/models/available'
    | '/api/user/credits'
    | '/api/webhooks/polar'
    | '/panel/endeksler/$id'
    | '/panel/sirketler/$id'
  id:
    | '__root__'
    | '/'
    | '/endeksler'
    | '/login'
    | '/nasil-calisir'
    | '/panel'
    | '/sektorler'
    | '/sirketler'
    | '/takip-listesi'
    | '/api/checkout'
    | '/panel/borsa'
    | '/panel/profil'
    | '/sektorler/$slug'
    | '/panel/'
    | '/api/ai/charge'
    | '/api/ai/pre-check'
    | '/api/auth/$'
    | '/api/models/available'
    | '/api/user/credits'
    | '/api/webhooks/polar'
    | '/panel/endeksler/$id'
    | '/panel/sirketler/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndekslerRoute: typeof EndekslerRoute
  LoginRoute: typeof LoginRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  PanelRoute: typeof PanelRouteWithChildren
  SektorlerRoute: typeof SektorlerRouteWithChildren
  SirketlerRoute: typeof SirketlerRoute
  TakipListesiRoute: typeof TakipListesiRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiAiChargeRoute: typeof ApiAiChargeRoute
  ApiAiPreCheckRoute: typeof ApiAiPreCheckRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiModelsAvailableRoute: typeof ApiModelsAvailableRoute
  ApiUserCreditsRoute: typeof ApiUserCreditsRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/takip-listesi': {
      id: '/takip-listesi'
      path: '/takip-listesi'
      fullPath: '/takip-listesi'
      preLoaderRoute: typeof TakipListesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sirketler': {
      id: '/sirketler'
      path: '/sirketler'
      fullPath: '/sirketler'
      preLoaderRoute: typeof SirketlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sektorler': {
      id: '/sektorler'
      path: '/sektorler'
      fullPath: '/sektorler'
      preLoaderRoute: typeof SektorlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endeksler': {
      id: '/endeksler'
      path: '/endeksler'
      fullPath: '/endeksler'
      preLoaderRoute: typeof EndekslerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/sektorler/$slug': {
      id: '/sektorler/$slug'
      path: '/$slug'
      fullPath: '/sektorler/$slug'
      preLoaderRoute: typeof SektorlerSlugRouteImport
      parentRoute: typeof SektorlerRoute
    }
    '/panel/profil': {
      id: '/panel/profil'
      path: '/profil'
      fullPath: '/panel/profil'
      preLoaderRoute: typeof PanelProfilRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/borsa': {
      id: '/panel/borsa'
      path: '/borsa'
      fullPath: '/panel/borsa'
      preLoaderRoute: typeof PanelBorsaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/sirketler/$id': {
      id: '/panel/sirketler/$id'
      path: '/sirketler/$id'
      fullPath: '/panel/sirketler/$id'
      preLoaderRoute: typeof PanelSirketlerIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/endeksler/$id': {
      id: '/panel/endeksler/$id'
      path: '/endeksler/$id'
      fullPath: '/panel/endeksler/$id'
      preLoaderRoute: typeof PanelEndekslerIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/credits': {
      id: '/api/user/credits'
      path: '/api/user/credits'
      fullPath: '/api/user/credits'
      preLoaderRoute: typeof ApiUserCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models/available': {
      id: '/api/models/available'
      path: '/api/models/available'
      fullPath: '/api/models/available'
      preLoaderRoute: typeof ApiModelsAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/pre-check': {
      id: '/api/ai/pre-check'
      path: '/api/ai/pre-check'
      fullPath: '/api/ai/pre-check'
      preLoaderRoute: typeof ApiAiPreCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/charge': {
      id: '/api/ai/charge'
      path: '/api/ai/charge'
      fullPath: '/api/ai/charge'
      preLoaderRoute: typeof ApiAiChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PanelRouteChildren {
  PanelBorsaRoute: typeof PanelBorsaRoute
  PanelProfilRoute: typeof PanelProfilRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelEndekslerIdRoute: typeof PanelEndekslerIdRoute
  PanelSirketlerIdRoute: typeof PanelSirketlerIdRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelBorsaRoute: PanelBorsaRoute,
  PanelProfilRoute: PanelProfilRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelEndekslerIdRoute: PanelEndekslerIdRoute,
  PanelSirketlerIdRoute: PanelSirketlerIdRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

interface SektorlerRouteChildren {
  SektorlerSlugRoute: typeof SektorlerSlugRoute
}

const SektorlerRouteChildren: SektorlerRouteChildren = {
  SektorlerSlugRoute: SektorlerSlugRoute,
}

const SektorlerRouteWithChildren = SektorlerRoute._addFileChildren(
  SektorlerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndekslerRoute: EndekslerRoute,
  LoginRoute: LoginRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  PanelRoute: PanelRouteWithChildren,
  SektorlerRoute: SektorlerRouteWithChildren,
  SirketlerRoute: SirketlerRoute,
  TakipListesiRoute: TakipListesiRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiAiChargeRoute: ApiAiChargeRoute,
  ApiAiPreCheckRoute: ApiAiPreCheckRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiModelsAvailableRoute: ApiModelsAvailableRoute,
  ApiUserCreditsRoute: ApiUserCreditsRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
