/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakipListesiRouteImport } from './routes/takip-listesi'
import { Route as SektorlerRouteImport } from './routes/sektorler'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as NedenJetborsaRouteImport } from './routes/neden-jetborsa'
import { Route as NasilCalisirRouteImport } from './routes/nasil-calisir'
import { Route as KurumsalRouteImport } from './routes/kurumsal'
import { Route as EndekslerRouteImport } from './routes/endeksler'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilIndexRouteImport } from './routes/profil.index'
import { Route as EndekslerIndexRouteImport } from './routes/endeksler.index'
import { Route as SektorlerSlugRouteImport } from './routes/sektorler.$slug'
import { Route as HisseTickerRouteImport } from './routes/hisse.$ticker'
import { Route as EndekslerIdRouteImport } from './routes/endeksler.$id'
import { Route as ApiTickersRouteImport } from './routes/api/tickers'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as HisseTickerIndexRouteImport } from './routes/hisse.$ticker.index'
import { Route as EndekslerIdIndexRouteImport } from './routes/endeksler.$id.index'
import { Route as HisseTickerTeknikAnalizRouteImport } from './routes/hisse.$ticker.teknik-analiz'
import { Route as EndekslerIdTeknikAnalizRouteImport } from './routes/endeksler.$id.teknik-analiz'
import { Route as ApiWebhooksPolarRouteImport } from './routes/api/webhooks/polar'
import { Route as ApiUserCreditsRouteImport } from './routes/api/user/credits'
import { Route as ApiModelsAvailableRouteImport } from './routes/api/models/available'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiPreCheckRouteImport } from './routes/api/ai/pre-check'
import { Route as ApiAiChargeRouteImport } from './routes/api/ai/charge'

const TakipListesiRoute = TakipListesiRouteImport.update({
  id: '/takip-listesi',
  path: '/takip-listesi',
  getParentRoute: () => rootRouteImport,
} as any)
const SektorlerRoute = SektorlerRouteImport.update({
  id: '/sektorler',
  path: '/sektorler',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const NedenJetborsaRoute = NedenJetborsaRouteImport.update({
  id: '/neden-jetborsa',
  path: '/neden-jetborsa',
  getParentRoute: () => rootRouteImport,
} as any)
const NasilCalisirRoute = NasilCalisirRouteImport.update({
  id: '/nasil-calisir',
  path: '/nasil-calisir',
  getParentRoute: () => rootRouteImport,
} as any)
const KurumsalRoute = KurumsalRouteImport.update({
  id: '/kurumsal',
  path: '/kurumsal',
  getParentRoute: () => rootRouteImport,
} as any)
const EndekslerRoute = EndekslerRouteImport.update({
  id: '/endeksler',
  path: '/endeksler',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilIndexRoute = ProfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfilRoute,
} as any)
const EndekslerIndexRoute = EndekslerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EndekslerRoute,
} as any)
const SektorlerSlugRoute = SektorlerSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SektorlerRoute,
} as any)
const HisseTickerRoute = HisseTickerRouteImport.update({
  id: '/hisse/$ticker',
  path: '/hisse/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const EndekslerIdRoute = EndekslerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EndekslerRoute,
} as any)
const ApiTickersRoute = ApiTickersRouteImport.update({
  id: '/api/tickers',
  path: '/api/tickers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const HisseTickerIndexRoute = HisseTickerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HisseTickerRoute,
} as any)
const EndekslerIdIndexRoute = EndekslerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EndekslerIdRoute,
} as any)
const HisseTickerTeknikAnalizRoute = HisseTickerTeknikAnalizRouteImport.update({
  id: '/teknik-analiz',
  path: '/teknik-analiz',
  getParentRoute: () => HisseTickerRoute,
} as any)
const EndekslerIdTeknikAnalizRoute = EndekslerIdTeknikAnalizRouteImport.update({
  id: '/teknik-analiz',
  path: '/teknik-analiz',
  getParentRoute: () => EndekslerIdRoute,
} as any)
const ApiWebhooksPolarRoute = ApiWebhooksPolarRouteImport.update({
  id: '/api/webhooks/polar',
  path: '/api/webhooks/polar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreditsRoute = ApiUserCreditsRouteImport.update({
  id: '/api/user/credits',
  path: '/api/user/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiModelsAvailableRoute = ApiModelsAvailableRouteImport.update({
  id: '/api/models/available',
  path: '/api/models/available',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPreCheckRoute = ApiAiPreCheckRouteImport.update({
  id: '/api/ai/pre-check',
  path: '/api/ai/pre-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChargeRoute = ApiAiChargeRouteImport.update({
  id: '/api/ai/charge',
  path: '/api/ai/charge',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/endeksler': typeof EndekslerRouteWithChildren
  '/kurumsal': typeof KurumsalRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/neden-jetborsa': typeof NedenJetborsaRoute
  '/profil': typeof ProfilRouteWithChildren
  '/sektorler': typeof SektorlerRouteWithChildren
  '/takip-listesi': typeof TakipListesiRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/tickers': typeof ApiTickersRoute
  '/endeksler/$id': typeof EndekslerIdRouteWithChildren
  '/hisse/$ticker': typeof HisseTickerRouteWithChildren
  '/sektorler/$slug': typeof SektorlerSlugRoute
  '/endeksler/': typeof EndekslerIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/api/ai/charge': typeof ApiAiChargeRoute
  '/api/ai/pre-check': typeof ApiAiPreCheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/models/available': typeof ApiModelsAvailableRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/endeksler/$id/teknik-analiz': typeof EndekslerIdTeknikAnalizRoute
  '/hisse/$ticker/teknik-analiz': typeof HisseTickerTeknikAnalizRoute
  '/endeksler/$id/': typeof EndekslerIdIndexRoute
  '/hisse/$ticker/': typeof HisseTickerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kurumsal': typeof KurumsalRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/neden-jetborsa': typeof NedenJetborsaRoute
  '/sektorler': typeof SektorlerRouteWithChildren
  '/takip-listesi': typeof TakipListesiRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/tickers': typeof ApiTickersRoute
  '/sektorler/$slug': typeof SektorlerSlugRoute
  '/endeksler': typeof EndekslerIndexRoute
  '/profil': typeof ProfilIndexRoute
  '/api/ai/charge': typeof ApiAiChargeRoute
  '/api/ai/pre-check': typeof ApiAiPreCheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/models/available': typeof ApiModelsAvailableRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/endeksler/$id/teknik-analiz': typeof EndekslerIdTeknikAnalizRoute
  '/hisse/$ticker/teknik-analiz': typeof HisseTickerTeknikAnalizRoute
  '/endeksler/$id': typeof EndekslerIdIndexRoute
  '/hisse/$ticker': typeof HisseTickerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/endeksler': typeof EndekslerRouteWithChildren
  '/kurumsal': typeof KurumsalRoute
  '/nasil-calisir': typeof NasilCalisirRoute
  '/neden-jetborsa': typeof NedenJetborsaRoute
  '/profil': typeof ProfilRouteWithChildren
  '/sektorler': typeof SektorlerRouteWithChildren
  '/takip-listesi': typeof TakipListesiRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/tickers': typeof ApiTickersRoute
  '/endeksler/$id': typeof EndekslerIdRouteWithChildren
  '/hisse/$ticker': typeof HisseTickerRouteWithChildren
  '/sektorler/$slug': typeof SektorlerSlugRoute
  '/endeksler/': typeof EndekslerIndexRoute
  '/profil/': typeof ProfilIndexRoute
  '/api/ai/charge': typeof ApiAiChargeRoute
  '/api/ai/pre-check': typeof ApiAiPreCheckRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/models/available': typeof ApiModelsAvailableRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/webhooks/polar': typeof ApiWebhooksPolarRoute
  '/endeksler/$id/teknik-analiz': typeof EndekslerIdTeknikAnalizRoute
  '/hisse/$ticker/teknik-analiz': typeof HisseTickerTeknikAnalizRoute
  '/endeksler/$id/': typeof EndekslerIdIndexRoute
  '/hisse/$ticker/': typeof HisseTickerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/endeksler'
    | '/kurumsal'
    | '/nasil-calisir'
    | '/neden-jetborsa'
    | '/profil'
    | '/sektorler'
    | '/takip-listesi'
    | '/api/checkout'
    | '/api/tickers'
    | '/endeksler/$id'
    | '/hisse/$ticker'
    | '/sektorler/$slug'
    | '/endeksler/'
    | '/profil/'
    | '/api/ai/charge'
    | '/api/ai/pre-check'
    | '/api/auth/$'
    | '/api/models/available'
    | '/api/user/credits'
    | '/api/webhooks/polar'
    | '/endeksler/$id/teknik-analiz'
    | '/hisse/$ticker/teknik-analiz'
    | '/endeksler/$id/'
    | '/hisse/$ticker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kurumsal'
    | '/nasil-calisir'
    | '/neden-jetborsa'
    | '/sektorler'
    | '/takip-listesi'
    | '/api/checkout'
    | '/api/tickers'
    | '/sektorler/$slug'
    | '/endeksler'
    | '/profil'
    | '/api/ai/charge'
    | '/api/ai/pre-check'
    | '/api/auth/$'
    | '/api/models/available'
    | '/api/user/credits'
    | '/api/webhooks/polar'
    | '/endeksler/$id/teknik-analiz'
    | '/hisse/$ticker/teknik-analiz'
    | '/endeksler/$id'
    | '/hisse/$ticker'
  id:
    | '__root__'
    | '/'
    | '/endeksler'
    | '/kurumsal'
    | '/nasil-calisir'
    | '/neden-jetborsa'
    | '/profil'
    | '/sektorler'
    | '/takip-listesi'
    | '/api/checkout'
    | '/api/tickers'
    | '/endeksler/$id'
    | '/hisse/$ticker'
    | '/sektorler/$slug'
    | '/endeksler/'
    | '/profil/'
    | '/api/ai/charge'
    | '/api/ai/pre-check'
    | '/api/auth/$'
    | '/api/models/available'
    | '/api/user/credits'
    | '/api/webhooks/polar'
    | '/endeksler/$id/teknik-analiz'
    | '/hisse/$ticker/teknik-analiz'
    | '/endeksler/$id/'
    | '/hisse/$ticker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EndekslerRoute: typeof EndekslerRouteWithChildren
  KurumsalRoute: typeof KurumsalRoute
  NasilCalisirRoute: typeof NasilCalisirRoute
  NedenJetborsaRoute: typeof NedenJetborsaRoute
  ProfilRoute: typeof ProfilRouteWithChildren
  SektorlerRoute: typeof SektorlerRouteWithChildren
  TakipListesiRoute: typeof TakipListesiRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiTickersRoute: typeof ApiTickersRoute
  HisseTickerRoute: typeof HisseTickerRouteWithChildren
  ApiAiChargeRoute: typeof ApiAiChargeRoute
  ApiAiPreCheckRoute: typeof ApiAiPreCheckRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiModelsAvailableRoute: typeof ApiModelsAvailableRoute
  ApiUserCreditsRoute: typeof ApiUserCreditsRoute
  ApiWebhooksPolarRoute: typeof ApiWebhooksPolarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/takip-listesi': {
      id: '/takip-listesi'
      path: '/takip-listesi'
      fullPath: '/takip-listesi'
      preLoaderRoute: typeof TakipListesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sektorler': {
      id: '/sektorler'
      path: '/sektorler'
      fullPath: '/sektorler'
      preLoaderRoute: typeof SektorlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neden-jetborsa': {
      id: '/neden-jetborsa'
      path: '/neden-jetborsa'
      fullPath: '/neden-jetborsa'
      preLoaderRoute: typeof NedenJetborsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasil-calisir': {
      id: '/nasil-calisir'
      path: '/nasil-calisir'
      fullPath: '/nasil-calisir'
      preLoaderRoute: typeof NasilCalisirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kurumsal': {
      id: '/kurumsal'
      path: '/kurumsal'
      fullPath: '/kurumsal'
      preLoaderRoute: typeof KurumsalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endeksler': {
      id: '/endeksler'
      path: '/endeksler'
      fullPath: '/endeksler'
      preLoaderRoute: typeof EndekslerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/': {
      id: '/profil/'
      path: '/'
      fullPath: '/profil/'
      preLoaderRoute: typeof ProfilIndexRouteImport
      parentRoute: typeof ProfilRoute
    }
    '/endeksler/': {
      id: '/endeksler/'
      path: '/'
      fullPath: '/endeksler/'
      preLoaderRoute: typeof EndekslerIndexRouteImport
      parentRoute: typeof EndekslerRoute
    }
    '/sektorler/$slug': {
      id: '/sektorler/$slug'
      path: '/$slug'
      fullPath: '/sektorler/$slug'
      preLoaderRoute: typeof SektorlerSlugRouteImport
      parentRoute: typeof SektorlerRoute
    }
    '/hisse/$ticker': {
      id: '/hisse/$ticker'
      path: '/hisse/$ticker'
      fullPath: '/hisse/$ticker'
      preLoaderRoute: typeof HisseTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endeksler/$id': {
      id: '/endeksler/$id'
      path: '/$id'
      fullPath: '/endeksler/$id'
      preLoaderRoute: typeof EndekslerIdRouteImport
      parentRoute: typeof EndekslerRoute
    }
    '/api/tickers': {
      id: '/api/tickers'
      path: '/api/tickers'
      fullPath: '/api/tickers'
      preLoaderRoute: typeof ApiTickersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hisse/$ticker/': {
      id: '/hisse/$ticker/'
      path: '/'
      fullPath: '/hisse/$ticker/'
      preLoaderRoute: typeof HisseTickerIndexRouteImport
      parentRoute: typeof HisseTickerRoute
    }
    '/endeksler/$id/': {
      id: '/endeksler/$id/'
      path: '/'
      fullPath: '/endeksler/$id/'
      preLoaderRoute: typeof EndekslerIdIndexRouteImport
      parentRoute: typeof EndekslerIdRoute
    }
    '/hisse/$ticker/teknik-analiz': {
      id: '/hisse/$ticker/teknik-analiz'
      path: '/teknik-analiz'
      fullPath: '/hisse/$ticker/teknik-analiz'
      preLoaderRoute: typeof HisseTickerTeknikAnalizRouteImport
      parentRoute: typeof HisseTickerRoute
    }
    '/endeksler/$id/teknik-analiz': {
      id: '/endeksler/$id/teknik-analiz'
      path: '/teknik-analiz'
      fullPath: '/endeksler/$id/teknik-analiz'
      preLoaderRoute: typeof EndekslerIdTeknikAnalizRouteImport
      parentRoute: typeof EndekslerIdRoute
    }
    '/api/webhooks/polar': {
      id: '/api/webhooks/polar'
      path: '/api/webhooks/polar'
      fullPath: '/api/webhooks/polar'
      preLoaderRoute: typeof ApiWebhooksPolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/credits': {
      id: '/api/user/credits'
      path: '/api/user/credits'
      fullPath: '/api/user/credits'
      preLoaderRoute: typeof ApiUserCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/models/available': {
      id: '/api/models/available'
      path: '/api/models/available'
      fullPath: '/api/models/available'
      preLoaderRoute: typeof ApiModelsAvailableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/pre-check': {
      id: '/api/ai/pre-check'
      path: '/api/ai/pre-check'
      fullPath: '/api/ai/pre-check'
      preLoaderRoute: typeof ApiAiPreCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/charge': {
      id: '/api/ai/charge'
      path: '/api/ai/charge'
      fullPath: '/api/ai/charge'
      preLoaderRoute: typeof ApiAiChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface EndekslerIdRouteChildren {
  EndekslerIdTeknikAnalizRoute: typeof EndekslerIdTeknikAnalizRoute
  EndekslerIdIndexRoute: typeof EndekslerIdIndexRoute
}

const EndekslerIdRouteChildren: EndekslerIdRouteChildren = {
  EndekslerIdTeknikAnalizRoute: EndekslerIdTeknikAnalizRoute,
  EndekslerIdIndexRoute: EndekslerIdIndexRoute,
}

const EndekslerIdRouteWithChildren = EndekslerIdRoute._addFileChildren(
  EndekslerIdRouteChildren,
)

interface EndekslerRouteChildren {
  EndekslerIdRoute: typeof EndekslerIdRouteWithChildren
  EndekslerIndexRoute: typeof EndekslerIndexRoute
}

const EndekslerRouteChildren: EndekslerRouteChildren = {
  EndekslerIdRoute: EndekslerIdRouteWithChildren,
  EndekslerIndexRoute: EndekslerIndexRoute,
}

const EndekslerRouteWithChildren = EndekslerRoute._addFileChildren(
  EndekslerRouteChildren,
)

interface ProfilRouteChildren {
  ProfilIndexRoute: typeof ProfilIndexRoute
}

const ProfilRouteChildren: ProfilRouteChildren = {
  ProfilIndexRoute: ProfilIndexRoute,
}

const ProfilRouteWithChildren =
  ProfilRoute._addFileChildren(ProfilRouteChildren)

interface SektorlerRouteChildren {
  SektorlerSlugRoute: typeof SektorlerSlugRoute
}

const SektorlerRouteChildren: SektorlerRouteChildren = {
  SektorlerSlugRoute: SektorlerSlugRoute,
}

const SektorlerRouteWithChildren = SektorlerRoute._addFileChildren(
  SektorlerRouteChildren,
)

interface HisseTickerRouteChildren {
  HisseTickerTeknikAnalizRoute: typeof HisseTickerTeknikAnalizRoute
  HisseTickerIndexRoute: typeof HisseTickerIndexRoute
}

const HisseTickerRouteChildren: HisseTickerRouteChildren = {
  HisseTickerTeknikAnalizRoute: HisseTickerTeknikAnalizRoute,
  HisseTickerIndexRoute: HisseTickerIndexRoute,
}

const HisseTickerRouteWithChildren = HisseTickerRoute._addFileChildren(
  HisseTickerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EndekslerRoute: EndekslerRouteWithChildren,
  KurumsalRoute: KurumsalRoute,
  NasilCalisirRoute: NasilCalisirRoute,
  NedenJetborsaRoute: NedenJetborsaRoute,
  ProfilRoute: ProfilRouteWithChildren,
  SektorlerRoute: SektorlerRouteWithChildren,
  TakipListesiRoute: TakipListesiRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiTickersRoute: ApiTickersRoute,
  HisseTickerRoute: HisseTickerRouteWithChildren,
  ApiAiChargeRoute: ApiAiChargeRoute,
  ApiAiPreCheckRoute: ApiAiPreCheckRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiModelsAvailableRoute: ApiModelsAvailableRoute,
  ApiUserCreditsRoute: ApiUserCreditsRoute,
  ApiWebhooksPolarRoute: ApiWebhooksPolarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
