/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelIndexRouteImport } from './routes/panel.index'
import { Route as PanelBorsaRouteImport } from './routes/panel.borsa'
import { Route as PanelSirketlerIdRouteImport } from './routes/panel.sirketler.$id'
import { Route as PanelEndekslerIdRouteImport } from './routes/panel.endeksler.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelBorsaRoute = PanelBorsaRouteImport.update({
  id: '/borsa',
  path: '/borsa',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSirketlerIdRoute = PanelSirketlerIdRouteImport.update({
  id: '/sirketler/$id',
  path: '/sirketler/$id',
  getParentRoute: () => PanelRoute,
} as any)
const PanelEndekslerIdRoute = PanelEndekslerIdRouteImport.update({
  id: '/endeksler/$id',
  path: '/endeksler/$id',
  getParentRoute: () => PanelRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/borsa': typeof PanelBorsaRoute
  '/panel/': typeof PanelIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/panel/endeksler/$id': typeof PanelEndekslerIdRoute
  '/panel/sirketler/$id': typeof PanelSirketlerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel/borsa': typeof PanelBorsaRoute
  '/panel': typeof PanelIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/panel/endeksler/$id': typeof PanelEndekslerIdRoute
  '/panel/sirketler/$id': typeof PanelSirketlerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/borsa': typeof PanelBorsaRoute
  '/panel/': typeof PanelIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/panel/endeksler/$id': typeof PanelEndekslerIdRoute
  '/panel/sirketler/$id': typeof PanelSirketlerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/panel'
    | '/panel/borsa'
    | '/panel/'
    | '/api/auth/$'
    | '/panel/endeksler/$id'
    | '/panel/sirketler/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/panel/borsa'
    | '/panel'
    | '/api/auth/$'
    | '/panel/endeksler/$id'
    | '/panel/sirketler/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/panel'
    | '/panel/borsa'
    | '/panel/'
    | '/api/auth/$'
    | '/panel/endeksler/$id'
    | '/panel/sirketler/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/': {
      id: '/panel/'
      path: '/'
      fullPath: '/panel/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/borsa': {
      id: '/panel/borsa'
      path: '/borsa'
      fullPath: '/panel/borsa'
      preLoaderRoute: typeof PanelBorsaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/sirketler/$id': {
      id: '/panel/sirketler/$id'
      path: '/sirketler/$id'
      fullPath: '/panel/sirketler/$id'
      preLoaderRoute: typeof PanelSirketlerIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/endeksler/$id': {
      id: '/panel/endeksler/$id'
      path: '/endeksler/$id'
      fullPath: '/panel/endeksler/$id'
      preLoaderRoute: typeof PanelEndekslerIdRouteImport
      parentRoute: typeof PanelRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PanelRouteChildren {
  PanelBorsaRoute: typeof PanelBorsaRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelEndekslerIdRoute: typeof PanelEndekslerIdRoute
  PanelSirketlerIdRoute: typeof PanelSirketlerIdRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelBorsaRoute: PanelBorsaRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelEndekslerIdRoute: PanelEndekslerIdRoute,
  PanelSirketlerIdRoute: PanelSirketlerIdRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PanelRoute: PanelRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
